### ISSUE TITLE
Article links to your repo and provides incorrect instructions

### ISSUE THREAD

**Issue by yusuf3a50** [TonyLHansen/raspberry-pi-safe-off-switch#12]
I know this is not directly related to your code. Your repo works brilliantly and I have it running on my pi, thank you. However, I initially followed [this article by Christian Crawley (2019)](https://www.makeuseof.com/tag/add-power-button-raspberry-pi/) which gives the following **incorrect** instructions:

> To ensure this works following a reboot, append /etc/rc.local:
`sudo nano /etc/rc.local`
> In the final line before the exit statement, add:
`echo '~pi/shutdown-press-simple.py'`
> Save and exit as before, then try the button out.

As your repo correctly details, a line should be added to /etc/rc.local before the `exit 0` line and this line should be:
`~pi/shutdown-press-simple.py &`

**Comment by TonyLHansen** [comment]
I did try to contact the author of that incorrect article. I see they haven't made any updates. Oh well.
