### ISSUE TITLE
Stretch Problem

### ISSUE THREAD

**Issue by sheridat** [TonyLHansen/raspberry-pi-safe-off-switch#2]
Please see the comment at the bottom of 
https://www.raspberrypi.org/magpi/off-switch-raspberry-pi from Aaron Henderson.
The comments suggests that the instructions as the stand will not work if the os is stretch.

**Comment by TonyLHansen** [comment]
I added a note to the text here and replied to the comment there.
Thanks for bringing the comment to my attention.
