### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by hichameyessou** [TonyLHansen/raspberry-pi-safe-off-switch#3]
In the progressive blinking sample, there are some character not recognized as ASCII (½ and ¼) that gives the following error
`SyntaxError: Non-ASCII character '\xc2' in file test.py on line 17, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

I would write just "a half second" and "one fourth".

**Comment by TonyLHansen** [comment]
Thanks for the report. These were in comments and weren't causing an error in my environment. But I've replaced them with their 1/2 and 1/4 ascii equivalents.
