### ISSUE TITLE
shutdown-led-simple.py kills wifi

### ISSUE THREAD

**Issue by kf4mot** [TonyLHansen/raspberry-pi-safe-off-switch#5]
On a Zero W running Buster I could get this working but it killed my wifi.
Changing the rc.local line of "~pi/shutdown-led-simple.py" to "python /home/pi/shutdown-led-simple.py &" is what it took to get it working again.

**Comment by TonyLHansen** [comment]
Yes, sorry. The & did get lost in one of the edits.
