### ISSUE TITLE
Clarify rc.local editing

### ISSUE THREAD

**Issue by kf4mot** [TonyLHansen/raspberry-pi-safe-off-switch#6]
I know that this tripped me up, and searching around the internet shows I'm not the only one.
The section on editing rc.local is giving terminal commands. NOT the lines that we should be adding to rc.local.

I entered these 2 lines into rc.local and it did not go well.
$ sudo su
# echo '~pi/shutdown-press-simple.py'  >> /etc/rc.local

**Comment by TonyLHansen** [comment]
you're right. I've updated the description to be more clear
