### ISSUE TITLE
Segmentation Fault Error

### ISSUE THREAD

**Issue by nbaddorf** [TonyLHansen/raspberry-pi-safe-off-switch#7]
Hi, I am trying to use your program on ubuntu mate 18.04 with a raspberry pi 3 b. I got the program installed, and when I run the program, and press the button, it says segmentation fault. I am not sure how to fix this. Thanks!

**Comment by TonyLHansen** [comment]
First step is to make sure that everything is as up-to-date as possible:

sudo update
sudo upgrade

If that fixes it, great!

If it doesn't, there are additional things you can try. Also, which particular script are you using?

**Comment by nbaddorf** [comment]
Thanks so much! Sorry for the late comment, I tried the update/upgrade and it fixed it. I thought I had already done that, but I guess not. Thanks!
