### ISSUE TITLE
Reboot/shutdown

### ISSUE THREAD

**Issue by tonyfdesign** [TonyLHansen/raspberry-pi-safe-off-switch#8]
Hello! Great information thank you! I wrote my script to look at PIN 3 and my button properly "shutsdown" but reboots the system. I'm hoping to use my button like an on/off where a second button press brings the Pi back to life. Is this possible?

Thanks in advance for your help.

**Comment by TonyLHansen** [comment]
1. Check the command that you are executing to make sure you are using one that shuts it down and not one that restarts. These python scripts are all just front ends to other system commands.
2. On most of the Raspberry Pis, you can use GPIO 3 for both a shutdown AND a reset.

`If you don't mind losing your I2C connectivity, an alternative choice would be GPIO 3, situated on pin 5. What is particularly nice about GPIO 3 is that it also acts as a reset pin when the computer is powered down. By using GPIO 3, you can use a single button for both an ON and OFF switch.`
