### ISSUE TITLE
rc.local

### ISSUE THREAD

**Issue by keleticsaba** [TonyLHansen/raspberry-pi-safe-off-switch#9]
"
Then add a line to the end of /etc/rc.local to run it at boot time:

$ sudo su
# echo '~pi/shutdown-press-simple.py'  >> /etc/rc.local
"

I think in the rc.local there should be something like this:

python3 /home/pi/shutdown-press-simple.py &

Because:
- it is python;
- and you must fork the command with "&" because rc.local can't exit ever with "0"

**Comment by TonyLHansen** [comment]
You're right in that there should be an & at the end of the command.
```
echo '~pi/shutdown-press-simple.py &' >> /etc/rc.local
```

However, all of the python scripts properly begin with
```
#!/usr/bin/env python3
```

so you do NOT need to know that the script is python or ruby or shell or .... Remember to do the `chmod a+x` and all will be fine.

My preference is actually to not include the `.py` as part of the filename when it is installed anywhere other than the source tree. The script should be self-contained with the knowledge on which interpreter should be used to run it, and not depend on someone knowing that this one needs to be run using python2 and this one needs to be run with python3 and this script needs bash and this script needs ksh and this script needs dash and ....

Hopefully you get what I'm saying.
